title: Canto Namespace Docs
description: Developer documentation for the Canto Namespace Subprotocol
theme: just-the-docs
favicon_ico: "/assets/CNP.jpg"
logo: "/assets/CNP.jpg"
image: "/assets/CNP.jpg"

url: https://docs.cantoname.build

permalink: pretty

aux_links:
  CNS Repo: https://github.com/mkt-market/canto-namespace-protocol
  Contribute to Docs: https://github.com/mkt-market/cns-docs
  Canto Identity Protocol Docs: https://docs.cantoidentity.build

plugins:
  - jekyll-seo-tag